spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:security
    username: root
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8081
