spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Admin123#
    url: jdbc:mysql://localhost:3306/dbo?createDatabaseIfNotExist=true
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
  batch:
    initialize-schema: always